/*
 * This source file was generated by the Gradle 'init' task
 */
package ai.tonic.fabricate.tools;

import java.io.IOException;
import java.util.List;
import java.util.Map;

/**
 * Main application class for the JSON flattening tool.
 * Processes JSONL files and outputs flattened JSON structures.
 */
public class App {
    public static void main(String[] args) {
        if (args.length == 0) {
            System.err.println("Usage: java App <jsonl-file-path>");
            System.err.println("Example: java App data/example.jsonl");
            System.exit(1);
        }
        
        try {
            String filePath = args[0];
            
            // Create a JsonFlattener instance and process the file
            JsonFlattener flattener = new JsonFlattener();
            List<Map<String, Object>> flattenedData = flattener.processJsonlFile(filePath);
            
            // Print the flattened result
            System.out.println(flattener.toPrettyJson(flattenedData));
            
        } catch (IOException e) {
            System.err.println("Error processing JSONL file: " + e.getMessage());
            e.printStackTrace();
        }
    }
}